% function for extraction of subject information for each experiments, 
% Eghbal Hosseini, 3/07/2020
% changelog: 
% HannaH 
% Eghbal hosseini: updates on saving, and sub_op generations.
% HannaH - Sept 23, 2020 -- added all info from Albany 
function ops_out=create_sub_operation_info_ALBANY(varargin)
p=inputParser();
addParameter(p, 'experiment', 'MITNLengthSentences');
addParameter(p, 'overwrite', true);
addParameter(p, 'save_path', '~/sub_op_info');
parse(p, varargin{:});
ops = p.Results;
ops_out=ops;
% create op info dir if id doesnt exist 
if exist(ops.save_path,'dir')==0,mkdir(ops.save_path);end
% library of experiment names and subjects 
exp_dat=[...
        ['MITNLengthSentences',{arrayfun(@(x) sprintf('AMC%03d',x),[82,83,86,91,92,96,97,99],'uniformoutput',false)}];...
        ['MIT_SWJN_audio_visual_task',{arrayfun(@(x) sprintf('AMC%03d',x),[85],'uniformoutput',false)}];...
        ['MITLangloc',{arrayfun(@(x) sprintf('AMC%03d',x),[82,86,88,91,92,96,97,99],'uniformoutput',false)}];...
        ['constituent-bounds',{arrayfun(@(x) sprintf('AMC%03d',x),[83,85,86,91,92,96,97,99,100],'uniformoutput',false)}];...
        ]; 

exp_subs=[exp_dat{contains(exp_dat(:,1),ops.experiment),2}]';
% generate all subject info 
all_sub_info=generate_all_sub_info();
% find subject with info file 
exp_sub_with_info=intersect(exp_subs,fields(all_sub_info));
% create and save sub_op_info
for k=1:length(exp_sub_with_info)
    %TODO - if channel labels is not empty, check that the number of labels
    %is equal to the number of ecog channels?
    %do some checks on the data?
    sub_cell=all_sub_info.(exp_sub_with_info{k});
    op_info=cell2struct(sub_cell(:,2),string([sub_cell{:,1}]));
    eval(strcat(op_info.sub_id,'_op_info','=op_info'));
    eval(sprintf('%s_op_info=op_info',op_info.sub_id));
    eval(sprintf('ops_out.%s_op_info=%s_op_info',op_info.sub_id,op_info.sub_id))
    if ops.overwrite
        save(sprintf('%s/%s_op_info.mat',ops.save_path,op_info.sub_id),sprintf('%s_op_info',op_info.sub_id));
    end 
end 
ops_out.exp_subs=exp_subs;
ops_out.exp_subs_wth_info=exp_sub_with_info;
end 

% routine for extracting experiments for a given subject
function exp_info=get_exp_for_sub(sub_id)

end

% creating a dictionarry of all the subjects and their information 
function all_sub_info=generate_all_sub_info()
    all_sub_info=struct;    
    %% AMC030
     sub_dat_template={{'sub_id'},      ['AMC030'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [68];...
            {'REF'},                    [24];...
            {'num_channels'},           [];...
            {'bad_channels'},           [];...
            {'cortical_channels'},      [1:93];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [arrayfun(@(x) sprintf('%d',x),[1:64]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RB_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LG_%d',x),[1:18]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PI_%d',x),[1:3]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SF_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('IP_%d',x),[1:3]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},     [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
       %% AMC031
       %% ref electrode is 99 for days1-3, 97 for day 4
     sub_dat_template={{'sub_id'},      ['AMC031'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [78];...
            {'REF'},                    [99,97];...
            {'num_channels'},           [];...
            {'bad_channels'},           [];...
            {'cortical_channels'},      [1:98];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [arrayfun(@(x) sprintf('LTG_%d',x),[1:78]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PS_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MS_%d',x),[1:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
       %% AMC037
       %% gnd electrode and ref electrode vary a lot over the sessions
     sub_dat_template={{'sub_id'},      ['AMC037'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [41,61,49];...
            {'REF'},                    [42,1,53];...
            {'num_channels'},           [];...
            {'bad_channels'},           [65,69,73,77,81,85,89,96,103,110,111,124,60,64];...
            {'cortical_channels'},      [1:134];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [193:198];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [arrayfun(@(x) sprintf('FG_%d',x),[1:48]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PG_%d',x),[2:5,7:10,12:15,17:20]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('TG_%d',x),[1:130]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FS_%d',x),[1:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
          %% AMC038
     sub_dat_template={{'sub_id'},      ['AMC038'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [16,1];...
            {'REF'},                    [16,1];...
            {'num_channels'},           [];...
            {'bad_channels'},           [16,21,26,28,53,55,56,59,60,64,75,84,92,99];...
            {'cortical_channels'},      [1:98];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [130];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [131];...
            {'channel_label'},          [arrayfun(@(x) sprintf('FG_%d',x),[1:20]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('TG_%d',x),[1:66]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FS_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:6]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
               %% AMC041
     sub_dat_template={{'sub_id'},      ['AMC041'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [43,59];...
            {'REF'},                    [59,43];...
            {'num_channels'},           [];...
            {'bad_channels'},           [68,69,70,76,59,75];...
            {'cortical_channels'},      [1:81];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:35]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:40]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('OS_%d',x),[1:6]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC044
     sub_dat_template={{'sub_id'},      ['AMC044'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left','right'];...
            {'GND'},                    ['skull'];...
            {'REF'},                    [];...
            {'num_channels'},           [];...
            {'bad_channels'},           [];...
            {'cortical_channels'},      [1:36];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [arrayfun(@(x) sprintf('RSA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RMA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RIA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RSP_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RIP_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LSA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LMA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LIA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LP_%d',x),[1:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
          %% AMC045
     sub_dat_template={{'sub_id'},      ['AMC045'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [52];...
            {'REF'},                    [46,34];...
            {'num_channels'},           [];...
            {'bad_channels'},           [];...
            {'cortical_channels'},      [1:79];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [81,133];...
            {'EMG_channels'},           [193:198, 129:134];...
            {'visual_trigger'},         [129,130];...
            {'button_trigger'},         [130];...
            {'buzzer_trigger'},         [131];...
            {'audio_trigger'},          [132];...
            {'channel_label'},          [arrayfun(@(x) sprintf('FG_%d',x),[5:8,12:48,52:55]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FP_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SF_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ID_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SL_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MT_%d',x),[1:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
          %% AMC047
     sub_dat_template={{'sub_id'},      ['AMC047'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [98];...
            {'REF'},                    [];...
            {'num_channels'},           [];...
            {'bad_channels'},           [16,56,68,72,73,75,78,82,85,86,87,98];...
            {'cortical_channels'},      [1:136];...
            {'skull_eeg_channels'},     [137:139];...
            {'microphone_channels'},    [197];...
            {'EMG_channels'},           [198:203];...
            {'visual_trigger'},         [193];...
            {'button_trigger'},         [194];...
            {'buzzer_trigger'},         [195];...
            {'audio_trigger'},          [196];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:66]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FPG_%d',x),[1:32]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('POG_%d',x),[2:6,8:12,14:18,20:24]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AM_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FPS_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('IPO_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SPO_%d',x),[1:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
          %% AMC048
     sub_dat_template={{'sub_id'},      ['AMC048'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [89,90];...
            {'REF'},                    [87,88];...
            {'num_channels'},           [];...
            {'bad_channels'},           [58,65,32,39,46,21,22,66];...
            {'cortical_channels'},      [1:90];...
            {'skull_eeg_channels'},     [91:94];...
            {'microphone_channels'},    [133];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [130];...
            {'buzzer_trigger'},         [131];...
            {'audio_trigger'},          [132];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:66]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:20]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('OS_%d',x),[1:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC056
     sub_dat_template={{'sub_id'},      ['AMC056'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [28];...
            {'REF'},                    [60];...
            {'num_channels'},           [];...
            {'bad_channels'},           [7,8,28,37,43,44,46,51,52,60,67,71,72,95,96,108,116];...
            {'cortical_channels'},      [1:117];...
            {'skull_eeg_channels'},     [118:120];...
            {'microphone_channels'},    [133];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [130];...
            {'buzzer_trigger'},         [131];...
            {'audio_trigger'},          [132];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:66]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[3:7,11:16,19:24,27:40,43:48,51:56,59:63]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('D_%d',x),[1:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC057
     sub_dat_template={{'sub_id'},      ['AMC057'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [117];...
            {'REF'},                    [99,95];...
            {'num_channels'},           [];...
            {'bad_channels'},           [30,38,39,50,54,27,38,74];...
            {'cortical_channels'},      [1:114];...
            {'skull_eeg_channels'},     [115:117];...
            {'microphone_channels'},    [133];...
            {'EMG_channels'},           [193:198];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [130];...
            {'buzzer_trigger'},         [131];...
            {'audio_trigger'},          [132];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:66]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AIT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AMT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AST_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('OS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTNE_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTSE_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTW_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC058
     sub_dat_template={{'sub_id'},      ['AMC058'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [98];...
            {'REF'},                    [93,94];...
            {'num_channels'},           [];...
            {'bad_channels'},           [22,23,26,64];...
            {'cortical_channels'},      [1:98];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [133];...
            {'EMG_channels'},           [193:198];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [130];...
            {'buzzer_trigger'},         [131];...
            {'audio_trigger'},          [132];...
            {'channel_label'},          [arrayfun(@(x) sprintf('FG_%d',x),[1:20]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FS_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('TG_%d',x),[1:28,32:35,39:42,46:49,53:56,60:63]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('TT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AT_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('OS_%d',x),[1:6]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC062
     sub_dat_template={{'sub_id'},      ['AMC062'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [];...
            {'REF'},                    [121,122,111];...
            {'num_channels'},           [];...
            {'bad_channels'},           [11,12,13,21:28,33,41:46,48,49,50,65:75,80,81,95:98,121:128,129,144,161,162,169,174,179,185,186,188,209];...
            {'cortical_channels'},      [1:256,1:49];...
            {'skull_eeg_channels'},     ['AUX45:AUX49'];...
            {'microphone_channels'},    ['AUX53'];...
            {'EMG_channels'},           ['AUX65:AUX70'];...
            {'visual_trigger'},         ['DigitInput1','AUX49'];...
            {'button_trigger'},         ['DigitInput2','AUX50'];...
            {'buzzer_trigger'},         ['DigitInput3','AUX51'];...
            {'audio_trigger'},          ['DigitInput4','AUX52'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:250]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RATS_%d',x),[2:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_RIFS_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_RATS_%d',x),[2:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_RAMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_RMMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_RPMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_LASS_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_LAS_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_LAMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_LPMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_LPSS_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AUX_GND_%d',x),[2:6]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC071
     sub_dat_template={{'sub_id'},      ['AMC071'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [138,141];...
            {'REF'},                    [31];...
            {'num_channels'},           [];...
            {'bad_channels'},           [27,37,138];...
            {'cortical_channels'},      [1:138];...
            {'skull_eeg_channels'},     [139:141];...
            {'microphone_channels'},    [197];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [193];...
            {'button_trigger'},         [194];...
            {'buzzer_trigger'},         [195];...
            {'audio_trigger'},          [196];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:66]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[3:8,11:16,19:24,27:32,35:40,43:48,51:57,59:64]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SS_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MS_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('IS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('OS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC078
     sub_dat_template={{'sub_id'},      ['AMC078'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [92,93];...
            {'REF'},                    [94,95];...
            {'num_channels'},           [];...
            {'bad_channels'},           [10,15,17,43,64,77,27,80,49,81,82,83,89,91,77:92];...
            {'cortical_channels'},      [1:92];...
            {'skull_eeg_channels'},     [93:101];...
            {'microphone_channels'},    [133];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [130];...
            {'buzzer_trigger'},         [131];...
            {'audio_trigger'},          [132];...
            {'channel_label'},          [arrayfun(@(x) sprintf('RPG_%d',x),[3:6,11:16,18:24,26:32,34:40,42:48]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RAG_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RPF_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RMF_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RIF_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RAT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RMT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RPT_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RSS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LI_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LP_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:10]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC079
     sub_dat_template={{'sub_id'},      ['AMC079'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [114];...
            {'REF'},                    [108];...
            {'num_channels'},           [];...
            {'bad_channels'},           [127:130,42,134,118,70,67,69];...
            {'cortical_channels'},      [1:134];...
            {'skull_eeg_channels'},     [135:137];...
            {'microphone_channels'},    [197];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [193];...
            {'button_trigger'},         [194];...
            {'buzzer_trigger'},         [195];...
            {'audio_trigger'},          [196];...
            {'channel_label'},          [arrayfun(@(x) sprintf('LTSG_%d',x),[1:28,32:35,39:42,46:49,53:56,60:63]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LTAG_%d',x),[4:6,10:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LTAS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LTMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LTPS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LHAD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LIAD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LIPD_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LFSG_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LFAG_%d',x),[20:23,28:30]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LFPG_%d',x),[51:56,59:64]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTPS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTPI_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTAS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTAM_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RTAI_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC081
     sub_dat_template={{'sub_id'},      ['AMC081'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [233];...
            {'REF'},                    [234];...
            {'num_channels'},           [];...
            {'bad_channels'},           [32,110,126,138,16,220,94,106,5];...
            {'cortical_channels'},      [1:232];...
            {'skull_eeg_channels'},     [233:234];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         ['DigitalInput1'];...
            {'button_trigger'},         ['DigitalInput2'];...
            {'buzzer_trigger'},         ['DigitalInput3'];...
            {'audio_trigger'},          ['DigitalInput4'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[5:10, 25:30,45:50,65:70,83:90,103:110,123:130,133:140,143:150,153:250]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PMS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('TG_%d',x),[15:20,35:40,55:60,75:80,93:100,113:120]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
    %% AMC082
    sub_dat={{'sub_id'},                ['AMC082'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [127];...
            {'REF'},                    [128];...
            {'num_channels'},           [128];...
            {'bad_channels'},           [33,75,101,128,16,80];...
            {'cortical_channels'},      [1:126];...
            {'skull_eeg_channels'},     [127:128];...
            {'microphone_channels'},    [192,129];...
            {'EMG_channels'},           [129:134];...
            {'visual_trigger'},         ['DigitalInput1'];...
            {'button_trigger'},         ['DigitalInput2'];...
            {'buzzer_trigger'},         ['DigitalInput3'];...
            {'audio_trigger'},          ['DigitalInput4'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('LG_%d',x),[1:64]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LFM_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LFS_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LFA_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LIP_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LIA_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RIH_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2,3]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};      
       
     % add subject to all fub definition
     all_sub_info.(sub_dat{1,2})=sub_dat;
     
     %% AMC083
     sub_dat_template={{'sub_id'},      ['AMC083'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [101];...
            {'REF'},                    [102];...
            {'num_channels'},           [];...
            {'bad_channels'},           [23,24,25,26,27,46,];...
            {'cortical_channels'},          [1:100];...
            {'skull_eeg_channels'},     [101:105];...
            {'microphone_channels'},    [129];...
            {'EMG_channels'},           [129:134];...
            {'visual_trigger'},         ['DigitalInput1'];...
            {'button_trigger'},         ['DigitalInput2'];...
            {'buzzer_trigger'},         ['DigitalInput3'];...
            {'audio_trigger'},          ['DigitalInput4'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:28,32:35,39:42,46:49,53:56,60:63]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ST_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('TT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AST_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MST_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PST_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AHD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PHD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AFS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AFG_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PFG_%d',x),[11:20]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:6]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
      %% AMC085
     sub_dat_template={{'sub_id'},      ['AMC085'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [104,65,35];...
            {'REF'},                    [103,102,65];...
            {'num_channels'},           [];...
            {'bad_channels'},           [21,47,65,86,97,29,6,16,82:85,90];...
            {'cortical_channels'},      [1:101];...
            {'skull_eeg_channels'},     [102:104];...
            {'microphone_channels'},    [129];...
            {'EMG_channels'},           [129:134];...
            {'visual_trigger'},         ['DigitalInput1'];...
            {'button_trigger'},         ['DigitalInput2'];...
            {'buzzer_trigger'},         ['DigitalInput3'];...
            {'audio_trigger'},          ['DigitalInput4'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:28,32:35,39,40,46,47,53,54,60,61]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:32]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ATG_%d',x),[36,37,44,45]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FP_%d',x),[1:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AST_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MST_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PST_%d',x),[2:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
    %% AMC086
    sub_dat_template={{'sub_id'},      ['AMC086'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [3];...
            {'REF'},                    [93];...
            {'num_channels'},           [];...
            {'bad_channels'},           [40,49,50,52:60];...
            {'cortical_channels'},      [1:92];...
            {'skull_eeg_channels'},     [93:95];...
            {'microphone_channels'},    [129];...
            {'EMG_channels'},           [129:134];...
            {'visual_trigger'},         ['DigitalInput1'];...
            {'button_trigger'},         ['DigitalInput2'];...
            {'buzzer_trigger'},         ['DigitalInput3'];...
            {'audio_trigger'},          ['DigitalInput4'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:15,17:27,32:34,40,41,46:48,53:55,60:62]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AT_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MT_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PT_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('UD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('HD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SS_%d',x),[3:6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PG_%d',x),[17:30]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
          %% AMC087
    sub_dat_template={{'sub_id'},      ['AMC087'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [96,112:114];...
            {'REF'},                    [112:114];...
            {'num_channels'},           [];...
            {'bad_channels'},           [85,96,109,110,84];...
            {'cortical_channels'},      [1:111];...
            {'skull_eeg_channels'},     [112:114];...
            {'microphone_channels'},    [129];...
            {'EMG_channels'},           [129:134];...
            {'visual_trigger'},         ['DigitalInput1'];...
            {'button_trigger'},         ['DigitalInput2'];...
            {'buzzer_trigger'},         ['DigitalInput3'];...
            {'audio_trigger'},          ['DigitalInput4'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:28,32:66]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('IG_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PG_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('IS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ID_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('HD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC088
    sub_dat_template={{'sub_id'},      ['AMC088'];...
            {'contact_modality'},       ['SEEG'];...
            {'hemisphere'},             ['left','right'];...
            {'GND'},                    [];...
            {'REF'},                    [];...
            {'num_channels'},           [];...
            {'bad_channels'},           [];...
            {'cortical_channels'},      [1:98];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [129,132];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [129];...
            {'buzzer_trigger'},         [130];...
            {'audio_trigger'},          [131];...
            {'channel_label'},          [arrayfun(@(x) sprintf('LTH_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LOH_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LH_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LPH_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RPPH_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ROH_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RH_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RPAH_%d',x),[1:14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:8]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
        %% AMC091
     sub_dat_template={{'sub_id'},      ['AMC091'];...
            {'contact_modality'},       ['SEEG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [65];...
            {'REF'},                    [66];...
            {'num_channels'},           [];...
            {'bad_channels'},           [15,80,97];...
            {'cortical_channels'},      [1:124];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [129,132];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [129];...
            {'button_trigger'},         [129];...
            {'buzzer_trigger'},         [130];...
            {'audio_trigger'},          [131];...
            {'channel_label'},          [arrayfun(@(x) sprintf('HIP_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('UNC_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AINS_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PINS_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MINS_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MHET_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AHET_%d',x),[1:14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PHET_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ATHET_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('STG_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LHET_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LAHET_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:5]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC092
     sub_dat_template={{'sub_id'},      ['AMC092'];...
            {'contact_modality'},       ['SEEG'];...
            {'hemisphere'},             ['left','right'];...
            {'GND'},                    [217];...
            {'REF'},                    [218,83];...
            {'num_channels'},             [];...
            {'bad_channels'},           [21,22,79,80,81,82,112,113,115,141:148,6,210];...
            {'cortical_channels'},      [1:216];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [197];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [193];...
            {'button_trigger'},         [194];...
            {'buzzer_trigger'},         [195];...
            {'audio_trigger'},          [196];...
            {'channel_label'},          [arrayfun(@(x) sprintf('LSP_%d',x),[1,3,5,7,9,10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LPCC_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LHH_%d',x),[1,3,5,7,9,11]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LPM_%d',x),[1,3,5,7]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LMC_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LOF_%d',x),[1:14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LHM_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LFP_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LAC_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RSP_%d',x),[1,3,5,7,8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RPC_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RHH_%d',x),[1,3,5,7,9,11,13]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ROF_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RHM_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RPM_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RMC_%d',x),[1:14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RFP_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RAC_%d',x),[1:14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LSP_%d',x),[2,4,6,8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LHH_%d',x),[2,4,6,8,10,12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('LPS_%d',x),[2,4,6,8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RSP_%d',x),[2,4,6]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('RHH_%d',x),[2,4,6,8,10,12,14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:8]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
      %% AMC093
     sub_dat_template={{'sub_id'},      ['AMC093'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['right'];...
            {'GND'},                    [217];...
            {'REF'},                    [218,83];...
            {'num_channels'},           [];...
            {'bad_channels'},           [21,22,79,80,81,82,112,113,115,141:148,210];...
            {'cortical_channels'},      [1:100];...
            {'skull_eeg_channels'},     [101:105];...
            {'microphone_channels'},    [133];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         ['DigitalInput1'];...
            {'button_trigger'},         ['DigitalInput2'];...
            {'buzzer_trigger'},         ['DigitalInput3'];...
            {'audio_trigger'},          ['DigitalInput4'];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TG_%d',x),[1:28,32:35,39:42,46:49,53:56,60:63]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('TP_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SAT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MAT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('IT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PT_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ID_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AHD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PHD_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('IFG_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('SFG_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:6]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC096
     sub_dat_template={{'sub_id'},      ['AMC096'];...
            {'contact_modality'},       ['SEEG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [129,97];...
            {'REF'},                    [136,98];...
            {'num_channels'},           [];...
            {'bad_channels'},           [97,102,98];...
            {'cortical_channels'},      [1:128];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [arrayfun(@(x) sprintf('PL_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PLM_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PC_%d',x),[1:14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('MC_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AC_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FP_%d',x),[1:14]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PPI_%d',x),[1:8]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('HT_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('BF_%d',x),[1:16]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('UNC_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('HH_%d',x),[1:12]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[1:8]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
          %% AMC097
     sub_dat_template={{'sub_id'},      ['AMC097'];...
            {'contact_modality'},       ['ECOG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [135];...
            {'REF'},                    [135];...
            {'num_channels'},           [];...
            {'bad_channels'},           [104,112,114,64,97,118];...
            {'cortical_channels'},      [1:132];...
            {'skull_eeg_channels'},     [133:135];...
            {'microphone_channels'},    [197];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [193];...
            {'button_trigger'},         [194];...
            {'buzzer_trigger'},         [195];...
            {'audio_trigger'},          [196];...
            {'channel_label'},          [arrayfun(@(x) sprintf('TPOG_%d',x),[1:64]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PTS_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ATS_%d',x),[1:10]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('FG_%d',x),[3:8,11:16,19:24,27:32,35:40,43:48]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('AITS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('ABTS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('PBTS_%d',x),[1:4]','uniformoutput',false);...
                                        arrayfun(@(x) sprintf('GND_%d',x),[2:4]','uniformoutput',false);...
                                        ];...
            {'visually_inspected'},       [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     
     %% AMC099
     sub_dat_template={{'sub_id'},      ['AMC099'];...
            {'contact_modality'},       ['SEEG'];...
            {'hemisphere'},             ['left'];...
            {'GND'},                    [1];...
            {'REF'},                    [];...
            {'num_channels'},           [];...
            {'bad_channels'},           [97,42,1,62,157];...
            {'cortical_channels'},      [];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [];...
            {'visually_inspected'},     [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC101
     sub_dat_template={{'sub_id'},      ['AMC101'];...
            {'contact_modality'},       ['SEEG'];...
            {'hemisphere'},             ['left','right'];...
            {'GND'},                    [];...
            {'REF'},                    [];...
            {'num_channels'},           [];...
            {'bad_channels'},           [];...
            {'cortical_channels'},      [];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [];...
            {'visually_inspected'},     [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     %% AMC
     sub_dat_template={{'sub_id'},      ['AMC'];...
            {'contact_modality'},       [];...
            {'hemisphere'},             [];...
            {'GND'},                    [];...
            {'REF'},                    [];...
            {'num_channels'},           [];...
            {'bad_channels'},           [];...
            {'cortical_channels'},      [];...
            {'skull_eeg_channels'},     [];...
            {'microphone_channels'},    [];...
            {'EMG_channels'},           [];...
            {'visual_trigger'},         [];...
            {'button_trigger'},         [];...
            {'buzzer_trigger'},         [];...
            {'audio_trigger'},          [];...
            {'channel_label'},          [];...
            {'visually_inspected'},     [0];...
            {'visually_inspected_by'},  ['N/A']};
        % add subject to all fub definition
     all_sub_info.(sub_dat_template{1,2})=sub_dat_template;
     
     

end 




%% TODO - don't save op info if it already exists!!
function trash_can()
%% AMC 26
op_info=struct;
op_info.subject_name='AMC026';

op_info.GND=[47];
op_info.Ref=1;
op_info.num_channels=128;
op_info.bad_channels = [108 121:128];

eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');
%% 
%% AMC 29
op_info=struct;
op_info.subject_name='AMC029';

op_info.GND=[7];
op_info.Ref=10;
op_info.num_channels=128;
op_info.bad_channels = [70:75 78:84 87:93 96:102 105:111 114:120 124];

eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');

%% 
%% AMC 30
op_info=struct;
op_info.subject_name='AMC030';

op_info.GND=[];
op_info.Ref=[];
op_info.num_channels=[];
op_info.bad_channels = [];

eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');
%% 
op_info=struct;
op_info.subject_name='AMC031';

op_info.GND=[78];
op_info.Ref=[97,99];
op_info.num_channels=112;
op_info.bad_channels = [29:31 37:38 61 72:73 77:80 97:112];

eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');
%% 
%% 
op_info=struct;
op_info.subject_name='AMC037';

op_info.GND=[41];
op_info.Ref=[42];
op_info.num_channels=134;
op_info.bad_channels = [3 5 7 67 80 99 124 133];

eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');
%% 
op_info=struct;
op_info.subject_name='AMC038';

op_info.GND=[16];
op_info.Ref=[1];
op_info.num_channels=98;
op_info.bad_channels = [21 26  53 56 60 84 92];

eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');
%% 
op_info=struct;
op_info.subject_name='AMC044';

op_info.GND=[];
op_info.Ref=[];
op_info.num_channels=68;
op_info.bad_channels = [5 7 10 37:68]; 

eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');

%%
%% AMC 82
op_info=struct;
op_info.subject_name='AMC082';

op_info.GND=[127];
op_info.Ref=[128];
op_info.num_channels=128;
op_info.cortical_channels=1:126;
op_info.skull_eeg_channels=127:128;
op_info.microphone_channels=[192,129];
op_info.EMG_channels=[129:134];
op_info.visual_trigger='DigIO_1';
op_info.button_trigger='DigIO_2';
op_info.buzzer_trigger='DigIO_3';
op_info.audio_trigger='DigIO_4';
op_info.bad_channels = [];
op_info.task_file_location='/DAY6/MITNaturalisticStoriesTask/ECOG001/';
labels= [arrayfun(@(x) sprintf('LG_%d',x),[1:64]','uniformoutput',false);...
        arrayfun(@(x) sprintf('LFM_%d',x),[1:16]','uniformoutput',false);...
        arrayfun(@(x) sprintf('LFS_%d',x),[1:16]','uniformoutput',false);...
        arrayfun(@(x) sprintf('LFA_%d',x),[1:4]','uniformoutput',false);...
        arrayfun(@(x) sprintf('LIP_%d',x),[1:12]','uniformoutput',false);...
        arrayfun(@(x) sprintf('LIA_%d',x),[1:10]','uniformoutput',false);...
        arrayfun(@(x) sprintf('RIH_%d',x),[1:4]','uniformoutput',false);...
        'GND';'GND'];

op_info.channel_labels=labels;
op_info.visually_inspected = 0;

op_info.seizure_channels=[121,122,105,106,87,95,96];
eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
save(strcat('~/Desktop/ECOG/subject_op_info_MASTER/',op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');
% op_info=struct;
% op_info.subject_name='AMC082';
% 
% op_info.GND=[];
% op_info.Ref=[];
% op_info.num_channels=128;
% op_info.bad_channels = []; 
% 
% eval(strcat(op_info.subject_name,'_op','.op_info=op_info'));
% save(strcat(save_path,op_info.subject_name,'_operation_info.mat'),strcat(op_info.subject_name,'_op'),'-v7.3');
end
